import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GlowBackground from "@/components/Gen/Glowing/GlowingEffects";
import ThemeProvider from "@/utils/config/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-3 bg-root-background `}>
        <ThemeProvider>
          <GlowBackground />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
